[package]
name = "minimal-zmq"
version = "0.1.0"
authors = ["Murph Murphy <murph@clurictec.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tmq = "0.2.1"
tokio = { version = "~0.2.9", features = ["rt-threaded", "macros"] }
